### ISSUE TITLE
Reinstall service unable to finish executing after firmware update

### ISSUE THREAD

**Issue by evie-lau** [evie-lau/Unifi-gateway-wpa-supplicant#2]
After firmware updates, the reinstall service is not finishing its job. It seems it's able to install wpa supplicant, and enable the service, but seems to die before the `start` command.
Have to manually start the wpa_supplicant service.
![image](https://github.com/user-attachments/assets/3fb3f4d0-682a-4be8-9070-62815d63d313)

**Comment by evie-lau** [comment]
Unsure if timing out, or OOM... maybe running too early on bootup?

Maybe can try delaying the service, or changing/removing the timeout

**Comment by evie-lau** [comment]
For comparison, a manual successful run of the reinstall service looks like this:

![image](https://github.com/user-attachments/assets/788ba0cc-9b14-4ad1-bedd-9aed460c6f98)

**Comment by evie-lau** [comment]
Decided to modify the reinstall service with the following:
- add `After=basic.target sysinit.target`
- add `Wants=basic.target sysinit.target`
- add `Restart=on-failure`

Haven't tested, but hopefully will fix the wpa_supplicant reinstall.
```
[Unit]
Description=Reinstall and start/enable wpa_supplicant
AssertPathExistsGlob=/etc/wpa_supplicant/packages/wpasupplicant*arm64.deb
AssertPathExistsGlob=/etc/wpa_supplicant/packages/libpcsclite1*arm64.deb
ConditionPathExists=!/sbin/wpa_supplicant
After=basic.target sysinit.target
Wants=basic.target sysinit.target

[Service]
Type=oneshot
ExecStartPre=/bin/sh -xc 'sleep 15 && dpkg -Ri /etc/wpa_supplicant/packages'
ExecStart=/bin/sh -xc 'systemctl start wpa_supplicant-wired@eth1'
ExecStartPost=/bin/sh -xc 'systemctl enable wpa_supplicant-wired@eth1'
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

**Comment by hunterjm** [comment]
These updates to the restart service did work for me on the latest software update for my UXG-Lite.

**Comment by evie-lau** [comment]
Thanks for confirming it works! I'll update the readme with some of these changes - hoping the `sleep 15` is unnecessary.

**Comment by evie-lau** [comment]
Confirmed these updates worked for me as well
